/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Admn
 */
public class MainLayout extends javax.swing.JFrame {

    /**
     * Creates new form MainLayout
     */
    public MainLayout() {
        initComponents();
        setLocationRelativeTo(null); // Hiển thị giữa màn hình
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLSach_icon = new javax.swing.JLabel();
        jLQlythuvien = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnQlySach = new javax.swing.JButton();
        btnQlyNhanvien = new javax.swing.JButton();
        btnQlyPhieuxuat = new javax.swing.JButton();
        btnQlyKhachhang = new javax.swing.JButton();
        btnQlyPhieunhap = new javax.swing.JButton();
        btnQlyThethuvien = new javax.swing.JButton();
        btnDangxuat = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnhienthi = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("MainLayout"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 800));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLSach_icon.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLSach_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sach_icon.png"))); // NOI18N
        jLSach_icon.setAlignmentX(0.5F);

        jLQlythuvien.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLQlythuvien.setText("QUẢN LÝ THƯ VIỆN");
        jLQlythuvien.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Menu.setBackground(new java.awt.Color(204, 255, 255));
        Menu.setSize(220, 200);

        btnQlySach.setBackground(new java.awt.Color(204, 255, 255));
        btnQlySach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnQlySach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/qlysach.png"))); // NOI18N
        btnQlySach.setText("Quản Lý Sách");
        buttonGroup1.add(btnQlySach);
        btnQlySach.setContentAreaFilled(false);
        btnQlySach.setOpaque(true);
        btnQlySach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQlySachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQlySachMouseExited(evt);
            }
        });
        btnQlySach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlySachActionPerformed(evt);
            }
        });

        btnQlyNhanvien.setBackground(new java.awt.Color(204, 255, 255));
        btnQlyNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnQlyNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nhanvien.png"))); // NOI18N
        btnQlyNhanvien.setText("Quản Lý Nhân Viên");
        buttonGroup1.add(btnQlyNhanvien);
        btnQlyNhanvien.setContentAreaFilled(false);
        btnQlyNhanvien.setOpaque(true);
        btnQlyNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQlyNhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQlyNhanvienMouseExited(evt);
            }
        });
        btnQlyNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlyNhanvienActionPerformed(evt);
            }
        });

        btnQlyPhieuxuat.setBackground(new java.awt.Color(204, 255, 255));
        btnQlyPhieuxuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnQlyPhieuxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/phieuxuat.png"))); // NOI18N
        btnQlyPhieuxuat.setText("Quản Lý Phiếu Xuất");
        buttonGroup1.add(btnQlyPhieuxuat);
        btnQlyPhieuxuat.setContentAreaFilled(false);
        btnQlyPhieuxuat.setOpaque(true);
        btnQlyPhieuxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQlyPhieuxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQlyPhieuxuatMouseExited(evt);
            }
        });
        btnQlyPhieuxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlyPhieuxuatActionPerformed(evt);
            }
        });

        btnQlyKhachhang.setBackground(new java.awt.Color(204, 255, 255));
        btnQlyKhachhang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnQlyKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/khachhang.png"))); // NOI18N
        btnQlyKhachhang.setText("Quản Lý Khách Hàng");
        buttonGroup1.add(btnQlyKhachhang);
        btnQlyKhachhang.setContentAreaFilled(false);
        btnQlyKhachhang.setOpaque(true);
        btnQlyKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQlyKhachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQlyKhachhangMouseExited(evt);
            }
        });
        btnQlyKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlyKhachhangActionPerformed(evt);
            }
        });

        btnQlyPhieunhap.setBackground(new java.awt.Color(204, 255, 255));
        btnQlyPhieunhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnQlyPhieunhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/phieunhap.png"))); // NOI18N
        btnQlyPhieunhap.setText("Quản Lý Phiếu Nhập");
        buttonGroup1.add(btnQlyPhieunhap);
        btnQlyPhieunhap.setContentAreaFilled(false);
        btnQlyPhieunhap.setOpaque(true);
        btnQlyPhieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQlyPhieunhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQlyPhieunhapMouseExited(evt);
            }
        });
        btnQlyPhieunhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlyPhieunhapActionPerformed(evt);
            }
        });

        btnQlyThethuvien.setBackground(new java.awt.Color(204, 255, 255));
        btnQlyThethuvien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnQlyThethuvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thethuvien.png"))); // NOI18N
        btnQlyThethuvien.setText("Quản Lý Thẻ Thư Viện");
        buttonGroup1.add(btnQlyThethuvien);
        btnQlyThethuvien.setContentAreaFilled(false);
        btnQlyThethuvien.setOpaque(true);
        btnQlyThethuvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQlyThethuvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQlyThethuvienMouseExited(evt);
            }
        });
        btnQlyThethuvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlyThethuvienActionPerformed(evt);
            }
        });

        btnDangxuat.setBackground(new java.awt.Color(204, 255, 255));
        btnDangxuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        btnDangxuat.setText("Đăng Xuất");
        buttonGroup1.add(btnDangxuat);
        btnDangxuat.setContentAreaFilled(false);
        btnDangxuat.setOpaque(true);
        btnDangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDangxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangxuatMouseExited(evt);
            }
        });
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(204, 255, 255));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icontk.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQlyThethuvien, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(btnQlySach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQlyNhanvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQlyKhachhang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQlyPhieunhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQlyPhieuxuat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQlySach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQlyNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnQlyPhieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnQlyPhieuxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQlyKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQlyThethuvien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(btnDangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLQlythuvien, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSach_icon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLQlythuvien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLSach_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        pnhienthi.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnhienthi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnhienthi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JPanel panel;
    
    private void showPanel(JPanel jpanel){
        panel = jpanel;
        pnhienthi.removeAll();
        pnhienthi.add(panel);
        pnhienthi.validate();
    }
    private void btnQlySachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlySachActionPerformed
        showPanel(new QuanLySach());
    }//GEN-LAST:event_btnQlySachActionPerformed

    private void btnQlySachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlySachMouseEntered
        btnQlySach.setBackground(Color.white);
    }//GEN-LAST:event_btnQlySachMouseEntered

    private void btnQlySachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlySachMouseExited
        btnQlySach.setBackground(Color.getColor("control"));
    }//GEN-LAST:event_btnQlySachMouseExited

    private void btnQlyPhieunhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlyPhieunhapMouseEntered
        btnQlyPhieunhap.setBackground(Color.white);
    }//GEN-LAST:event_btnQlyPhieunhapMouseEntered

    private void btnQlyPhieunhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlyPhieunhapMouseExited
        btnQlyPhieunhap.setBackground(Color.getColor("control"));
    }//GEN-LAST:event_btnQlyPhieunhapMouseExited

    private void btnQlyPhieuxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlyPhieuxuatMouseEntered
        btnQlyPhieuxuat.setBackground(Color.white);
    }//GEN-LAST:event_btnQlyPhieuxuatMouseEntered

    private void btnQlyPhieuxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlyPhieuxuatMouseExited
        btnQlyPhieuxuat.setBackground(Color.getColor("control"));
    }//GEN-LAST:event_btnQlyPhieuxuatMouseExited

    private void btnQlyKhachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlyKhachhangMouseEntered
        btnQlyKhachhang.setBackground(Color.white);
    }//GEN-LAST:event_btnQlyKhachhangMouseEntered

    private void btnQlyKhachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlyKhachhangMouseExited
        btnQlyKhachhang.setBackground(Color.getColor("control"));
    }//GEN-LAST:event_btnQlyKhachhangMouseExited

    private void btnQlyThethuvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlyThethuvienMouseEntered
        btnQlyThethuvien.setBackground(Color.white);
    }//GEN-LAST:event_btnQlyThethuvienMouseEntered

    private void btnQlyThethuvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlyThethuvienMouseExited
        btnQlyThethuvien.setBackground(Color.getColor("control"));
    }//GEN-LAST:event_btnQlyThethuvienMouseExited

    private void btnDangxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangxuatMouseEntered
        btnDangxuat.setBackground(Color.white);
    }//GEN-LAST:event_btnDangxuatMouseEntered

    private void btnDangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangxuatMouseExited
        btnDangxuat.setBackground(Color.getColor("control"));
    }//GEN-LAST:event_btnDangxuatMouseExited

    private void btnQlyNhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlyNhanvienMouseEntered
        btnQlyNhanvien.setBackground(Color.white);
    }//GEN-LAST:event_btnQlyNhanvienMouseEntered

    private void btnQlyNhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQlyNhanvienMouseExited
        btnQlyNhanvien.setBackground(Color.getColor("control"));
    }//GEN-LAST:event_btnQlyNhanvienMouseExited

    private void btnQlyNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlyNhanvienActionPerformed
        showPanel(new QuanLyNhanVien());
    }//GEN-LAST:event_btnQlyNhanvienActionPerformed

    private void btnQlyPhieunhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlyPhieunhapActionPerformed
        showPanel(new QuanLyPhieuNhap());
    }//GEN-LAST:event_btnQlyPhieunhapActionPerformed

    private void btnQlyPhieuxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlyPhieuxuatActionPerformed
        showPanel(new QuanLyPhieuXuat());
    }//GEN-LAST:event_btnQlyPhieuxuatActionPerformed

    private void btnQlyKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlyKhachhangActionPerformed
        showPanel(new QuanLyKhachHang());
    }//GEN-LAST:event_btnQlyKhachhangActionPerformed

    private void btnQlyThethuvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlyThethuvienActionPerformed
        showPanel(new QuanLyTheThuVien());
    }//GEN-LAST:event_btnQlyThethuvienActionPerformed

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        login dangnhap = new login(); // open JFrame MainLayout
        dangnhap.show(); // display MainLayout 
        dispose(); // close login
    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        showPanel(new ThongKe());
    }//GEN-LAST:event_btnThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                new MainLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnQlyKhachhang;
    private javax.swing.JButton btnQlyNhanvien;
    private javax.swing.JButton btnQlyPhieunhap;
    private javax.swing.JButton btnQlyPhieuxuat;
    private javax.swing.JButton btnQlySach;
    private javax.swing.JButton btnQlyThethuvien;
    private javax.swing.JButton btnThongKe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLQlythuvien;
    private javax.swing.JLabel jLSach_icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnhienthi;
    // End of variables declaration//GEN-END:variables

    
}
