/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Admn
 */
public class QuanLyNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTimkiemNhanvien = new javax.swing.JTextField();
        btnThemNhanvien = new javax.swing.JButton();
        btnSuaNhanvien = new javax.swing.JButton();
        btnXoaNhanvien = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNhanvien = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản Lý Nhân Viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        setMaximumSize(new java.awt.Dimension(650, 500));

        txtTimkiemNhanvien.setBackground(new java.awt.Color(204, 255, 204));
        txtTimkiemNhanvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimkiemNhanvien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtTimkiemNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemNhanvienActionPerformed(evt);
            }
        });

        btnThemNhanvien.setBackground(new java.awt.Color(204, 204, 255));
        btnThemNhanvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemNhanvien.setForeground(new java.awt.Color(102, 102, 102));
        btnThemNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/them.png"))); // NOI18N
        btnThemNhanvien.setText("Thêm");
        btnThemNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhanvienActionPerformed(evt);
            }
        });

        btnSuaNhanvien.setBackground(new java.awt.Color(204, 204, 255));
        btnSuaNhanvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSuaNhanvien.setForeground(new java.awt.Color(102, 102, 102));
        btnSuaNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sua.png"))); // NOI18N
        btnSuaNhanvien.setText("Sửa");

        btnXoaNhanvien.setBackground(new java.awt.Color(204, 204, 255));
        btnXoaNhanvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoaNhanvien.setForeground(new java.awt.Color(102, 102, 102));
        btnXoaNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa.png"))); // NOI18N
        btnXoaNhanvien.setText("Xóa");

        jTableNhanvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableNhanvien.setForeground(new java.awt.Color(204, 204, 204));
        jTableNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Số điện thoại", "CCCD", "Email"
            }
        ));
        jTableNhanvien.setPreferredSize(new java.awt.Dimension(525, 80));
        jScrollPane1.setViewportView(jTableNhanvien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimkiemNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnThemNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnSuaNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnXoaNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtTimkiemNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimkiemNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemNhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimkiemNhanvienActionPerformed

    private void btnThemNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemNhanvienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaNhanvien;
    private javax.swing.JButton btnThemNhanvien;
    private javax.swing.JButton btnXoaNhanvien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNhanvien;
    private javax.swing.JTextField txtTimkiemNhanvien;
    // End of variables declaration//GEN-END:variables
}
