/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Admn
 */
public class QuanLyKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyKhachHang
     */
    public QuanLyKhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTimkiemKhachhang = new javax.swing.JTextField();
        btnThemKhachhang = new javax.swing.JButton();
        btnSuaKhachhang = new javax.swing.JButton();
        btnXoaKhachhang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKhachhang = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản Lý Khách Hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        txtTimkiemKhachhang.setBackground(new java.awt.Color(204, 255, 204));
        txtTimkiemKhachhang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimkiemKhachhang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtTimkiemKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemKhachhangActionPerformed(evt);
            }
        });

        btnThemKhachhang.setBackground(new java.awt.Color(204, 204, 255));
        btnThemKhachhang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemKhachhang.setForeground(new java.awt.Color(102, 102, 102));
        btnThemKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/them.png"))); // NOI18N
        btnThemKhachhang.setText("Thêm");
        btnThemKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKhachhangActionPerformed(evt);
            }
        });

        btnSuaKhachhang.setBackground(new java.awt.Color(204, 204, 255));
        btnSuaKhachhang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSuaKhachhang.setForeground(new java.awt.Color(102, 102, 102));
        btnSuaKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sua.png"))); // NOI18N
        btnSuaKhachhang.setText("Sửa");

        btnXoaKhachhang.setBackground(new java.awt.Color(204, 204, 255));
        btnXoaKhachhang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoaKhachhang.setForeground(new java.awt.Color(102, 102, 102));
        btnXoaKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa.png"))); // NOI18N
        btnXoaKhachhang.setText("Xóa");

        jTableKhachhang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableKhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Email", "CCCD", "Giới tính", "Số điện thoại", "Mã thẻ"
            }
        ));
        jScrollPane1.setViewportView(jTableKhachhang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTimkiemKhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnThemKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnSuaKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnXoaKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(txtTimkiemKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(218, 218, 218)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimkiemKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemKhachhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimkiemKhachhangActionPerformed

    private void btnThemKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKhachhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemKhachhangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaKhachhang;
    private javax.swing.JButton btnThemKhachhang;
    private javax.swing.JButton btnXoaKhachhang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKhachhang;
    private javax.swing.JTextField txtTimkiemKhachhang;
    // End of variables declaration//GEN-END:variables
}
