/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Admn
 */
public class SuaSach extends javax.swing.JDialog {

    /**
     * Creates new form SuaSach
     */
    public SuaSach() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuasach2 = new javax.swing.JPanel();
        jPanelSuasach1 = new javax.swing.JPanel();
        jLabelSuasach = new javax.swing.JLabel();
        jLabelSuasach1 = new javax.swing.JLabel();
        jLabelSuasach2 = new javax.swing.JLabel();
        jLabelSuasach3 = new javax.swing.JLabel();
        jLabelSuasach4 = new javax.swing.JLabel();
        jLabelSuasach5 = new javax.swing.JLabel();
        jLabelSuasach6 = new javax.swing.JLabel();
        jLabelSuasach7 = new javax.swing.JLabel();
        jLabelSuasach8 = new javax.swing.JLabel();
        txtSuasach2 = new javax.swing.JTextField();
        txtSuasach3 = new javax.swing.JTextField();
        txtSuasach1 = new javax.swing.JTextField();
        txtSuasach4 = new javax.swing.JTextField();
        txSuasach5 = new javax.swing.JTextField();
        txtSuasach6 = new javax.swing.JTextField();
        txtSuasach7 = new javax.swing.JTextField();
        txtSuasach8 = new javax.swing.JTextField();
        btnCapnhatSuasach = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSuasach2.setBackground(new java.awt.Color(255, 255, 204));

        jPanelSuasach1.setBackground(new java.awt.Color(204, 255, 255));

        jLabelSuasach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSuasach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSuasach.setText("Sửa Sách");

        javax.swing.GroupLayout jPanelSuasach1Layout = new javax.swing.GroupLayout(jPanelSuasach1);
        jPanelSuasach1.setLayout(jPanelSuasach1Layout);
        jPanelSuasach1Layout.setHorizontalGroup(
            jPanelSuasach1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuasach1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabelSuasach, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSuasach1Layout.setVerticalGroup(
            jPanelSuasach1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSuasach, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabelSuasach1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSuasach1.setText("Mã sách:");

        jLabelSuasach2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSuasach2.setText("Tên sách:");

        jLabelSuasach3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSuasach3.setText("Thể loại:");

        jLabelSuasach4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSuasach4.setText("Tác giả:");

        jLabelSuasach5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSuasach5.setText("Nhà xuất bản:");

        jLabelSuasach6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSuasach6.setText("Năm xuất bản:");

        jLabelSuasach7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSuasach7.setText("Giá:");

        jLabelSuasach8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSuasach8.setText("Số lượng:");

        txtSuasach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuasach2ActionPerformed(evt);
            }
        });

        txtSuasach3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuasach3ActionPerformed(evt);
            }
        });

        txtSuasach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuasach1ActionPerformed(evt);
            }
        });

        txtSuasach4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuasach4ActionPerformed(evt);
            }
        });

        txSuasach5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSuasach5ActionPerformed(evt);
            }
        });

        txtSuasach6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuasach6ActionPerformed(evt);
            }
        });

        txtSuasach7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuasach7ActionPerformed(evt);
            }
        });

        txtSuasach8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuasach8ActionPerformed(evt);
            }
        });

        btnCapnhatSuasach.setBackground(new java.awt.Color(204, 255, 255));
        btnCapnhatSuasach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapnhatSuasach.setText("Cập Nhật");
        btnCapnhatSuasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatSuasachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSuasach2Layout = new javax.swing.GroupLayout(jPanelSuasach2);
        jPanelSuasach2.setLayout(jPanelSuasach2Layout);
        jPanelSuasach2Layout.setHorizontalGroup(
            jPanelSuasach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSuasach1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSuasach2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelSuasach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCapnhatSuasach)
                    .addGroup(jPanelSuasach2Layout.createSequentialGroup()
                        .addGroup(jPanelSuasach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSuasach8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSuasach2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSuasach1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSuasach3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSuasach4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSuasach5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSuasach6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSuasach7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelSuasach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSuasach2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSuasach3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSuasach1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSuasach4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txSuasach5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSuasach6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSuasach7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSuasach8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelSuasach2Layout.setVerticalGroup(
            jPanelSuasach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuasach2Layout.createSequentialGroup()
                .addComponent(jPanelSuasach1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSuasach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSuasach1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuasach1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanelSuasach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSuasach2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuasach2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelSuasach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSuasach3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuasach3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSuasach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSuasach4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuasach4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSuasach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSuasach5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txSuasach5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSuasach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSuasach6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuasach6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSuasach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSuasach7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuasach7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSuasach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSuasach8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuasach8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnCapnhatSuasach)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSuasach2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSuasach2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSuasach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuasach2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuasach2ActionPerformed

    private void txtSuasach3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuasach3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuasach3ActionPerformed

    private void txtSuasach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuasach1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuasach1ActionPerformed

    private void txtSuasach4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuasach4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuasach4ActionPerformed

    private void txSuasach5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSuasach5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSuasach5ActionPerformed

    private void txtSuasach6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuasach6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuasach6ActionPerformed

    private void txtSuasach7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuasach7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuasach7ActionPerformed

    private void txtSuasach8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuasach8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuasach8ActionPerformed

    private void btnCapnhatSuasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatSuasachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapnhatSuasachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhatSuasach;
    private javax.swing.JLabel jLabelSuasach;
    private javax.swing.JLabel jLabelSuasach1;
    private javax.swing.JLabel jLabelSuasach2;
    private javax.swing.JLabel jLabelSuasach3;
    private javax.swing.JLabel jLabelSuasach4;
    private javax.swing.JLabel jLabelSuasach5;
    private javax.swing.JLabel jLabelSuasach6;
    private javax.swing.JLabel jLabelSuasach7;
    private javax.swing.JLabel jLabelSuasach8;
    private javax.swing.JPanel jPanelSuasach1;
    private javax.swing.JPanel jPanelSuasach2;
    private javax.swing.JTextField txSuasach5;
    private javax.swing.JTextField txtSuasach1;
    private javax.swing.JTextField txtSuasach2;
    private javax.swing.JTextField txtSuasach3;
    private javax.swing.JTextField txtSuasach4;
    private javax.swing.JTextField txtSuasach6;
    private javax.swing.JTextField txtSuasach7;
    private javax.swing.JTextField txtSuasach8;
    // End of variables declaration//GEN-END:variables
}
