/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Admn
 */
public class ThemSach extends javax.swing.JDialog {

    /**
     * Creates new form ThemSach
     */
    public ThemSach() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelThemSach2 = new javax.swing.JPanel();
        jPanelThemSach1 = new javax.swing.JPanel();
        jLabelThemSach = new javax.swing.JLabel();
        jLabelThemSach1 = new javax.swing.JLabel();
        jLabelThemSach2 = new javax.swing.JLabel();
        jLabelThemSach3 = new javax.swing.JLabel();
        jLabelThemSach4 = new javax.swing.JLabel();
        jLabelThemSach5 = new javax.swing.JLabel();
        jLabelThemSach6 = new javax.swing.JLabel();
        jLabelThemSach7 = new javax.swing.JLabel();
        jLabelThemSach8 = new javax.swing.JLabel();
        txtThemsach2 = new javax.swing.JTextField();
        txtThemsach3 = new javax.swing.JTextField();
        txtThemsach1 = new javax.swing.JTextField();
        txtThemsach4 = new javax.swing.JTextField();
        txtThemsach5 = new javax.swing.JTextField();
        txtThemsach6 = new javax.swing.JTextField();
        txtThemsach7 = new javax.swing.JTextField();
        txtThemsach8 = new javax.swing.JTextField();
        btnCapnhatThemsach = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelThemSach2.setBackground(new java.awt.Color(255, 255, 204));

        jPanelThemSach1.setBackground(new java.awt.Color(204, 255, 255));

        jLabelThemSach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelThemSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelThemSach.setText("Thêm Sách");

        javax.swing.GroupLayout jPanelThemSach1Layout = new javax.swing.GroupLayout(jPanelThemSach1);
        jPanelThemSach1.setLayout(jPanelThemSach1Layout);
        jPanelThemSach1Layout.setHorizontalGroup(
            jPanelThemSach1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemSach1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabelThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelThemSach1Layout.setVerticalGroup(
            jPanelThemSach1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelThemSach, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jLabelThemSach1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelThemSach1.setText("Mã sách:");

        jLabelThemSach2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelThemSach2.setText("Tên sách:");

        jLabelThemSach3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelThemSach3.setText("Thể loại:");

        jLabelThemSach4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelThemSach4.setText("Tác giả:");

        jLabelThemSach5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelThemSach5.setText("Nhà xuất bản:");

        jLabelThemSach6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelThemSach6.setText("Năm xuất bản:");

        jLabelThemSach7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelThemSach7.setText("Giá:");

        jLabelThemSach8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelThemSach8.setText("Số lượng:");

        txtThemsach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemsach2ActionPerformed(evt);
            }
        });

        txtThemsach3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemsach3ActionPerformed(evt);
            }
        });

        txtThemsach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemsach1ActionPerformed(evt);
            }
        });

        txtThemsach4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemsach4ActionPerformed(evt);
            }
        });

        txtThemsach5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemsach5ActionPerformed(evt);
            }
        });

        txtThemsach6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemsach6ActionPerformed(evt);
            }
        });

        txtThemsach7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemsach7ActionPerformed(evt);
            }
        });

        txtThemsach8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemsach8ActionPerformed(evt);
            }
        });

        btnCapnhatThemsach.setBackground(new java.awt.Color(204, 255, 255));
        btnCapnhatThemsach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapnhatThemsach.setText("Cập Nhật");
        btnCapnhatThemsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatThemsachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelThemSach2Layout = new javax.swing.GroupLayout(jPanelThemSach2);
        jPanelThemSach2.setLayout(jPanelThemSach2Layout);
        jPanelThemSach2Layout.setHorizontalGroup(
            jPanelThemSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelThemSach1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelThemSach2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelThemSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCapnhatThemsach)
                    .addGroup(jPanelThemSach2Layout.createSequentialGroup()
                        .addGroup(jPanelThemSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelThemSach8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelThemSach2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelThemSach1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelThemSach3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelThemSach4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelThemSach5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelThemSach6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelThemSach7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelThemSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThemsach2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThemsach3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThemsach1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThemsach4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThemsach5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThemsach6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThemsach7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThemsach8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelThemSach2Layout.setVerticalGroup(
            jPanelThemSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemSach2Layout.createSequentialGroup()
                .addComponent(jPanelThemSach1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelThemSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelThemSach1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThemsach1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanelThemSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelThemSach2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThemsach2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelThemSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelThemSach3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThemsach3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelThemSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelThemSach4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThemsach4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThemSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelThemSach5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThemsach5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThemSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelThemSach6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThemsach6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThemSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelThemSach7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThemsach7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThemSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelThemSach8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThemsach8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnCapnhatThemsach)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelThemSach2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelThemSach2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtThemsach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemsach2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThemsach2ActionPerformed

    private void txtThemsach3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemsach3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThemsach3ActionPerformed

    private void txtThemsach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemsach1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThemsach1ActionPerformed

    private void txtThemsach4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemsach4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThemsach4ActionPerformed

    private void txtThemsach5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemsach5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThemsach5ActionPerformed

    private void txtThemsach6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemsach6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThemsach6ActionPerformed

    private void txtThemsach7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemsach7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThemsach7ActionPerformed

    private void txtThemsach8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemsach8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThemsach8ActionPerformed

    private void btnCapnhatThemsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatThemsachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapnhatThemsachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhatThemsach;
    private javax.swing.JLabel jLabelThemSach;
    private javax.swing.JLabel jLabelThemSach1;
    private javax.swing.JLabel jLabelThemSach2;
    private javax.swing.JLabel jLabelThemSach3;
    private javax.swing.JLabel jLabelThemSach4;
    private javax.swing.JLabel jLabelThemSach5;
    private javax.swing.JLabel jLabelThemSach6;
    private javax.swing.JLabel jLabelThemSach7;
    private javax.swing.JLabel jLabelThemSach8;
    private javax.swing.JPanel jPanelThemSach1;
    private javax.swing.JPanel jPanelThemSach2;
    private javax.swing.JTextField txtThemsach1;
    private javax.swing.JTextField txtThemsach2;
    private javax.swing.JTextField txtThemsach3;
    private javax.swing.JTextField txtThemsach4;
    private javax.swing.JTextField txtThemsach5;
    private javax.swing.JTextField txtThemsach6;
    private javax.swing.JTextField txtThemsach7;
    private javax.swing.JTextField txtThemsach8;
    // End of variables declaration//GEN-END:variables
}
